const String imagePath = "assets/images";

class ImageAssets {
  static const String logo = "$imagePath/logo.png";
  static const String splash = "$imagePath/splash.png";
  static const String splash_logo = "$imagePath/splash_logo.png";
  static const String profile = "$imagePath/profile.png";
  static const String look_job = "$imagePath/look_job.png";
  static const String course = "$imagePath/course.png";
  static const String available_job = "$imagePath/available_job.png";
  static const String company1 = "$imagePath/company1.png";
  static const String company2 = "$imagePath/company2.png";
  static const String company3 = "$imagePath/company3.png";
  static const String company4 = "$imagePath/company4.png";
  static const String company5 = "$imagePath/company5.png";
  static const String checked_sigin = "$imagePath/checked_sigin.png";
  static const String appbar_logo = "$imagePath/appbar_logo.png";
  static const String initiative = "$imagePath/initiative.png";
  static const String settings = "$imagePath/settings.png";
  static const String home = "$imagePath/home.png";
  static const String aboutus = "$imagePath/aboutus.png";
  static const String privacy = "$imagePath/privacy.png";
  static const String terms = "$imagePath/terms.png";
  static const String call = "$imagePath/phone.png";
  static const String language = "$imagePath/language.png";
  static const String logout = "$imagePath/logout.png";
  static const String share = "$imagePath/share.png";
  static const String placeholder ="$imagePath/placeholder.png";
  static const String congratulations = "$imagePath/congratulations.png";
  static const String error = "$imagePath/error.png";
  static const String editIcon = "$imagePath/edit.png";
  static const String secondary_logo = "$imagePath/secondary_logo.png";
  static const String google_play = "$imagePath/play_store.png";
  static const String apple_store = "$imagePath/apple_store.png";
  static const String huawei_store = "$imagePath/huawie.png";
  static const String app_slogan = "$imagePath/app_slogan.png";
  static const String suggested_jobs = "$imagePath/suggested_jobs.png";
  static const String tga_white_new = "$imagePath/tga_white_new.png";
}